name: Entregables

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write


    steps:
      - name: Paso 1 Checkout repo
        uses: actions/checkout@v4

      - name: Paso 2 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'
      - name: Paso 3 - crea entorno virtual
        run: python -m venv venv
      - name: Paso 4 - activar entorno virtual
        run: ./venv/Scripts/activate   
      - name: Paso 5 - actualizar pip
        run: pip install --upgrade pip
      - name: Paso 6 - instalar dependencias
        run: pip install -e .
      - name: Paso 7 - Ejecutar Script entregable_uno
        run: python entregable_uno.py
      - name: Paso 8 - Validar resultados (debe decir 'Validación: OK')
        run: |
          $out = python validador_uno.py
          Write-Host $out
          if ($out -notmatch 'Validación: OK') {
            throw "El validador no pasó. Revisa datos_out.txt y grafico_out.jpg."
          }
        shell: pwsh

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ntregable uno: genera y valida datos_out.txt y grafico_out.jpg"
          commit_user_name: Andres Callejas [GitHub Actions]
          commit_user_email: andres.callejas@iudigital.edu.co
          commit_author: Andres Callejas <andres.callejas@iudigital.edu.co>
