name: Entregables

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4

      - name: Step 2 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.2"

      - name: Step 3 - Upgrade pip
        run: python -m pip install --upgrade pip
        shell: pwsh

      - name: Step 4 - Install deps
        run: |
          python -m pip install matplotlib
        shell: pwsh

      - name: Step 5 - Ensure input file
        run: |
          if (-not (Test-Path -Path "datos_in.txt")) {
            "40 98725654 645564564" | Out-File -Encoding utf8 datos_in.txt
          }
        shell: pwsh

      - name: Step 6 - Run entregable_uno.py
        run: python entregable_uno.py
        shell: pwsh

      - name: Step 7 - Validate
        run: |
          $out = python validador_uno.py
          Write-Host $out
          if ($out -match 'Nota:\s*5') {
            Write-Host 'Entregable uno  OK'
          } else {
            throw "Entregable uno  OK error"
          }
        shell: pwsh

      - name: Step 8 - Auto-commit & push (git)
        if: success()
        run: |
          git config user.name "Andres Callejas [GitHub Actions]"
          git config user.email "andres.callejas@iudigital.edu.co"
          git add datos_out.txt grafico_out.jpg
          git commit -m "CI: generate and validate datos_out.txt and grafico_out.jpg" || echo "Nada que commitear"
          git push origin "${{ github.ref_name }}"
        shell: bash
